import type { PostInput } from "../../src/schemas";

/**
 * The previous site rendered every blog card into the same generic modal body
 * ("Introduction / Key Takeaways / Conclusion" boilerplate). That is textbook
 * thin, duplicated content and it actively suppressed the blog in search.
 *
 * Each post below now carries a real, unique Markdown article rendered on its
 * own indexable /blog/[slug] page. Treat these as first drafts in your voice —
 * edit them in the admin panel, add your own war stories, and they will do real
 * work for long-tail search traffic.
 */
export const posts: PostInput[] = [
  {
    title: "Building Scalable Mobile Applications with React Native",
    slug: "building-scalable-mobile-applications-with-react-native",
    excerpt:
      "The architectural decisions that decide whether a React Native app stays maintainable at scale — navigation, state, module boundaries and the render budget.",
    category: "Mobile Development",
    tags: ["React Native", "Mobile", "Architecture"],
    readTimeMinutes: 8,
    coverImage:
      "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=1200&h=630&fit=crop",
    publishedAt: new Date("2024-10-15"),
    published: true,
    featured: true,
    seoTitle: "Scalable React Native Architecture: A Practical Guide",
    seoDescription:
      "Navigation, state management, module boundaries and render performance — the four decisions that determine whether a React Native app scales.",
    body: [
      "Most React Native apps do not fail because of React Native. They fail because four decisions were made casually in week one and never revisited. Here is how I approach each of them.",
      "",
      "## 1. Draw module boundaries before you need them",
      "",
      "A `screens/` folder that grows to sixty files is not architecture. Organise by feature instead:",
      "",
      "```",
      "src/",
      "  features/",
      "    onboarding/    components, hooks, api, types",
      "    checkout/",
      "    profile/",
      "  shared/          design system, utilities, api client",
      "```",
      "",
      "The rule that keeps this honest: a feature may import from `shared/`, never from another feature. When two features genuinely need the same thing, it moves to `shared/`. That single constraint prevents the tangle that makes large apps unsafe to change.",
      "",
      "## 2. Pick the smallest state tool that works",
      "",
      "Redux is not the default any more, and it should not be. Most screens need three kinds of state, and they want different tools:",
      "",
      "- **Server state** — anything fetched. Use a query library with caching and invalidation. Do not hand-roll loading flags.",
      "- **Global client state** — session, theme, feature flags. A small store is plenty.",
      "- **Local state** — form inputs, toggles. `useState`, and nothing more.",
      "",
      "The common mistake is putting server state in a global store. You end up writing cache invalidation by hand, badly, forever.",
      "",
      "## 3. Treat navigation as part of the architecture",
      "",
      "Navigation structure leaks into everything: deep links, auth gating, analytics, back behaviour. Decide early whether auth is a separate navigator swapped at the root (usually right) or a redirect inside a shared stack (usually painful). Define your deep link scheme up front, even if you ship it later, because retrofitting URLs onto a screen hierarchy that was never designed for them is genuinely miserable.",
      "",
      "## 4. Respect the render budget",
      "",
      "A 60fps target gives you 16ms per frame. On the mid-range Android devices most of your users actually own, you get less. Three habits cover most of it:",
      "",
      "- Use `FlatList` with `keyExtractor` and stable item components. Never `.map()` a long list.",
      "- Memoise list items and the callbacks passed into them, or memoisation does nothing.",
      "- Keep animations on the native driver. A JS-driven animation stutters the moment the bridge gets busy.",
      "",
      "## Measure on the worst device you support",
      "",
      "Profiling on a flagship phone tells you almost nothing. Keep a cheap Android device on your desk and test on it regularly. The performance problems that matter show up there first — usually months before a user reports them.",
      "",
      "None of this is exotic. It is just decided deliberately rather than by accident, which is the entire difference between an app that scales and one that has to be rewritten.",
    ].join("\n"),
  },
  {
    title: "The Future of Frontend Development in 2025",
    slug: "future-of-frontend-development-2025",
    excerpt:
      "Server components, AI-assisted workflows and the quiet return of the multi-page app — what actually changed in frontend, and what was noise.",
    category: "Web Development",
    tags: ["Frontend", "Trends", "AI"],
    readTimeMinutes: 6,
    coverImage:
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&h=630&fit=crop",
    publishedAt: new Date("2024-10-10"),
    published: true,
    featured: false,
    seoTitle: "Frontend Development Trends That Actually Matter",
    seoDescription:
      "Server components, AI-assisted coding and the return of server rendering — a working developer's read on where frontend is heading.",
    body: [
      "Every year brings a pile of frontend predictions and most of them age badly. Here are the shifts I think are real, judged by whether they changed how I actually build things.",
      "",
      "## The server came back",
      "",
      "The biggest change is philosophical. For a decade the answer to everything was *ship more JavaScript to the client*. That has reversed. Server components, streaming and partial hydration all push work back to the server, and the client bundle shrinks accordingly.",
      "",
      "This matters most for content sites. A portfolio, a blog, a marketing site — none of these needed to be single-page applications, and making them SPAs cost real search visibility. Rendering HTML on the server and hydrating only the interactive parts is simply the correct default now.",
      "",
      "## AI changed the boring parts, not the hard parts",
      "",
      "AI assistants are genuinely good at scaffolding, translating between frameworks, writing tests for existing code, and explaining unfamiliar codebases. They are still weak at the things that decide whether a project succeeds: knowing which abstraction will survive the next six months of requirements, and knowing what to leave out.",
      "",
      "The practical effect is that the cost of writing code fell faster than the cost of deciding what to write. Judgment became the bottleneck. That is a good outcome for anyone who has been doing this a while.",
      "",
      "## CSS quietly got very good",
      "",
      "Container queries, `:has()`, cascade layers, subgrid and native nesting landed with far less fanfare than they deserved. A great deal of what used to require a JavaScript layout observer is now four lines of CSS. If your mental model of CSS is from 2019, it is worth a weekend to refresh it — this is the highest-leverage catch-up available to most frontend developers right now.",
      "",
      "## What I would ignore",
      "",
      "Framework churn for its own sake. The gap between the top handful of frameworks is now much smaller than the gap between a well-architected app and a badly-architected one in the same framework. Choose one with a healthy ecosystem, learn it deeply, and spend your remaining attention on fundamentals: accessibility, performance budgets and data modelling.",
      "",
      "Those have outlasted every framework cycle so far, and they will outlast this one.",
    ].join("\n"),
  },
  {
    title: "Mastering UI/UX Design Principles for Developers",
    slug: "ui-ux-design-principles-for-developers",
    excerpt:
      "You do not need to become a designer. You need five principles — spacing, hierarchy, contrast, alignment and feedback — applied consistently.",
    category: "Design",
    tags: ["UI/UX", "Design", "Best Practices"],
    readTimeMinutes: 10,
    coverImage:
      "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=1200&h=630&fit=crop",
    publishedAt: new Date("2024-10-05"),
    published: true,
    featured: false,
    seoTitle: "UI/UX Design Principles Every Developer Should Know",
    seoDescription:
      "Five practical design principles — spacing, hierarchy, contrast, alignment and feedback — that let developers build interfaces that look designed.",
    body: [
      "Developer-built interfaces usually fail in the same predictable ways. The good news is that fixing them is mechanical. You do not need taste; you need five rules applied consistently.",
      "",
      "## 1. Space is the whole game",
      "",
      "If an interface looks amateur, spacing is the cause about 80% of the time. Pick a scale — 4, 8, 12, 16, 24, 32, 48, 64 — and use only those values. Never `margin-top: 13px`.",
      "",
      "The rule that fixes most layouts: **related things sit closer together than unrelated things**. A label should be nearer its input than the input above it. When grouping is ambiguous, the eye has to work, and the interface feels cluttered even when everything is technically aligned.",
      "",
      "## 2. Build a real type hierarchy",
      "",
      "Three or four sizes is plenty. What separates levels is not just size but weight and colour together. A heading at 24px semibold in full-contrast text against body copy at 16px regular at 70% opacity reads clearly. The same heading at 17px does not.",
      "",
      "Set line height by role: roughly 1.2 for headings, 1.5–1.6 for body text. And cap line length at 60–75 characters. Long lines are the single most common readability failure on developer-built sites.",
      "",
      "## 3. Contrast is accessibility, not decoration",
      "",
      "Body text needs a 4.5:1 contrast ratio; large text needs 3:1. Light grey text on white is the most common violation in modern design, and it fails real users on real screens in real daylight.",
      "",
      "Also: never encode meaning in colour alone. An error state that is only red is invisible to a colourblind user. Add an icon, a label, or both.",
      "",
      "## 4. Align to something",
      "",
      "Every element should line up with another element. Pick a grid, keep left edges consistent, and stop centring things arbitrarily. Centred text is for short headings, not paragraphs.",
      "",
      "## 5. Acknowledge every interaction",
      "",
      "Anything clickable needs hover, focus and active states. Anything slow needs a loading state. Anything that can fail needs an error state that says what to do next, not just what went wrong.",
      "",
      "Focus states in particular get deleted for looking ugly. Do not delete them — style them. Keyboard users cannot navigate your interface without them, and removing the outline is one of the most common accessibility regressions there is.",
      "",
      "## The shortcut",
      "",
      "Constrain your options. A defined spacing scale, four type sizes, a fixed palette and two shadow levels will get you a long way. Most bad interfaces are not bad because the designer made poor choices — they are bad because nobody made choices at all, and every component invented its own values.",
    ].join("\n"),
  },
  {
    title: "Optimizing React Performance: Tips and Tricks",
    slug: "optimizing-react-performance",
    excerpt:
      "Profile first. Then fix the three things that are almost always the cause: unstable props, unnecessary context reads, and rendering lists you should be virtualising.",
    category: "React",
    tags: ["React", "Performance", "Optimization"],
    readTimeMinutes: 7,
    coverImage:
      "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=1200&h=630&fit=crop",
    publishedAt: new Date("2024-09-28"),
    published: true,
    featured: false,
    seoTitle: "React Performance Optimization: A Practical Guide",
    seoDescription:
      "How to profile React apps and fix the real causes of slow renders — unstable props, context over-subscription and unvirtualised lists.",
    body: [
      "Most React performance advice starts with `useMemo`. That is the wrong place to start, and premature memoisation makes codebases worse while rarely making them faster.",
      "",
      "## Profile before you touch anything",
      "",
      "Open React DevTools, enable *Highlight updates when components render*, and use the app. You are looking for components that flash on interactions that should not affect them. That flash is your problem. Everything else is speculation.",
      "",
      "Then use the Profiler tab to record an interaction and read the flame graph. Sort by render duration. Fix the top item. Re-measure. Stop when it feels fast.",
      "",
      "## Cause 1: unstable props",
      "",
      "This is the big one:",
      "",
      "```jsx",
      "// New object and new function on every parent render.",
      "<Chart config={{ height: 300 }} onSelect={(id) => setActive(id)} />",
      "```",
      "",
      "`Chart` re-renders every time regardless of whether it is wrapped in `React.memo`, because both props are new references each pass. Hoist the object out of the component, and wrap the callback in `useCallback` with correct dependencies.",
      "",
      "The general rule: `React.memo` does nothing useful unless the props are referentially stable. Memoising a component while passing it fresh object literals is pure overhead.",
      "",
      "## Cause 2: context over-subscription",
      "",
      "Every consumer of a context re-renders when any part of its value changes. A single context holding user, theme and cart means changing the cart re-renders everything that reads the theme.",
      "",
      "Split contexts by update frequency. Things that change constantly should not share a provider with things that change once per session.",
      "",
      "## Cause 3: rendering lists you should virtualise",
      "",
      "Rendering 5,000 rows creates 5,000 DOM subtrees, and the browser pays for all of them on every layout. Virtualisation renders only what is visible. Past roughly a few hundred rows, it is not an optimisation, it is a requirement.",
      "",
      "## Then, the free wins",
      "",
      "- **Code splitting.** Route-level `lazy()` plus `Suspense` cuts initial bundle size with almost no effort.",
      "- **Defer offscreen work.** Modals, tab panels and below-the-fold widgets do not need to be in the first bundle.",
      "- **Ship less JavaScript.** Check your bundle analyser. A date library or icon set imported wholesale is often larger than your entire application code.",
      "",
      "## Know when to stop",
      "",
      "Perceived performance is what users judge. An app that renders in 200ms with an instant loading skeleton feels faster than one that renders in 150ms with a blank white screen. Optimise the experience, not the number.",
    ].join("\n"),
  },
  {
    title: "Building a Successful Career as a Frontend Developer",
    slug: "building-a-career-as-a-frontend-developer",
    excerpt:
      "What actually compounds over a frontend career — fundamentals over frameworks, shipped work over certificates, and communication as a technical skill.",
    category: "Career",
    tags: ["Career", "Tips", "Growth"],
    readTimeMinutes: 9,
    coverImage:
      "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1200&h=630&fit=crop",
    publishedAt: new Date("2024-09-20"),
    published: true,
    featured: false,
    seoTitle: "How to Build a Frontend Development Career That Compounds",
    seoDescription:
      "Career advice for frontend developers: which skills compound, how to build a portfolio that converts, and why communication is a technical skill.",
    body: [
      "I have been building for the web professionally for over five years, working with teams in Sri Lanka and the UK, and running my own studio alongside employment. This is what I would tell someone starting now.",
      "",
      "## Fundamentals compound; frameworks depreciate",
      "",
      "Time spent on HTML semantics, CSS layout, the event loop, HTTP and browser rendering keeps paying out for a decade. Time spent memorising a specific framework's API pays out until that API changes.",
      "",
      "This is not an argument against learning frameworks — you need one, deeply. It is an argument about *ratio*. Developers who understand the platform pick up new frameworks in a fortnight. Developers who only know one framework start from zero each time the industry moves.",
      "",
      "## A portfolio of three real things beats twenty tutorials",
      "",
      "Nobody hiring is impressed by another to-do app. What works is depth: three projects you can talk about for twenty minutes each. What the constraint was, what you tried that failed, why you chose the approach you did, what you would change now.",
      "",
      "That last question is the one that separates candidates. Being able to critique your own work honestly signals more seniority than the work itself.",
      "",
      "## Communication is a technical skill",
      "",
      "The developers who progressed fastest around me were not the strongest coders. They were the ones who could write a clear proposal, explain a trade-off to a non-technical stakeholder, and disagree with a decision without making it personal.",
      "",
      "Concretely: write the summary before the meeting. Say what you recommend and why, not just what the options are. When you are blocked, say so early with what you have already tried.",
      "",
      "## Working remotely across time zones",
      "",
      "Much of my work has been remote for teams in other countries. The thing that makes it work is not availability — it is being *legible*. Write things down. Leave your work in a state someone can pick up. Over-communicate status so nobody has to ask.",
      "",
      "Distance amplifies whatever your habits already are. Disorganised in an office is survivable; disorganised remote is not.",
      "",
      "## On freelancing",
      "",
      "Freelancing is two jobs: the engineering and the business. Underpricing is the standard early mistake, and it does not just cost money — it attracts the clients who cause the most trouble. Price against value delivered, scope in writing, and take a deposit. Every horror story I know traces back to skipping one of those three.",
      "",
      "## The long game",
      "",
      "Careers are not built from a single leap. They are built from being reliably good over years, in public where possible, and staying curious after it stops being novel. That is unglamorous advice. It is also the advice that actually works.",
    ].join("\n"),
  },
  {
    title: "Integrating AI Features into Modern Web Applications",
    slug: "integrating-ai-features-into-web-applications",
    excerpt:
      "A practical guide to shipping AI features that survive contact with real users — streaming, cost control, failure handling and prompt injection.",
    category: "AI & ML",
    tags: ["AI", "Machine Learning", "APIs"],
    readTimeMinutes: 11,
    coverImage:
      "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=1200&h=630&fit=crop",
    publishedAt: new Date("2024-09-15"),
    published: true,
    featured: true,
    seoTitle: "How to Integrate AI Features Into a Web App Properly",
    seoDescription:
      "Streaming responses, cost control, graceful failure and prompt injection defence — what it takes to ship production AI features.",
    body: [
      "Adding an AI feature to a web app is easy. Adding one that stays fast, affordable and safe under real traffic is the actual work. Here is what I have learned shipping them.",
      "",
      "## Keep API keys on the server. Always.",
      "",
      "This should be obvious and it is still the most common mistake. A model API key in client-side code is a key anyone can extract from the network tab and spend on your account. Every model call goes through your own backend route. No exceptions.",
      "",
      "That server route is also where you enforce everything else that follows.",
      "",
      "## Stream, or the feature will feel broken",
      "",
      "A model response can take several seconds. A spinner for eight seconds reads as a hang; the same eight seconds with text appearing token by token reads as fast. Streaming is not a nice-to-have — it is the difference between a feature people use and one they abandon.",
      "",
      "## Control cost at the door",
      "",
      "Usage-based pricing plus an unauthenticated endpoint is a bill waiting to happen. At minimum:",
      "",
      "- **Rate limit per user and per IP.** Cheap to add, saves you from both abuse and runaway loops.",
      "- **Cap input length.** Truncate or reject oversized inputs before they reach the model.",
      "- **Cache deterministic results.** Identical questions do not need to be re-answered from scratch.",
      "- **Match the model to the task.** Classification and extraction rarely need your most capable model. Reserve that for work that genuinely benefits.",
      "",
      "## Design for the failure cases",
      "",
      "Model APIs time out, rate limit and occasionally return something unusable. Decide up front what the user sees in each case. A feature that silently does nothing on failure trains people to distrust it.",
      "",
      "And if you need structured output, validate it. Ask for JSON, parse it defensively, and validate against a schema before it touches your database. Do not assume the shape is correct because it usually is.",
      "",
      "## Treat user input as hostile",
      "",
      "Prompt injection is the genuinely new security problem here. If your prompt includes user-supplied text — or worse, text fetched from a URL the user provided — that content can attempt to override your instructions.",
      "",
      "The mitigations that help: keep untrusted content clearly delimited and labelled as data rather than instructions; never grant the model authority it should not have (if it cannot be allowed to delete records, do not give it a delete tool); and validate every tool call server-side against the *user's* permissions, not the model's request.",
      "",
      "The rule I work to: treat model output the way you treat form input from a stranger.",
      "",
      "## Be honest in the interface",
      "",
      "Label AI-generated content. Make it correctable. Do not present a probabilistic answer with the visual confidence of a database lookup. Users forgive a system that is occasionally wrong and says so; they do not forgive one that was confidently wrong and hid it.",
      "",
      "## Start narrow",
      "",
      "The AI features that work are specific: summarise this document, extract these fields, draft a reply in this tone. Broad open-ended assistants are much harder to make reliably good. Pick one task, make it genuinely excellent, then expand.",
    ].join("\n"),
  },
  {
    title: "TypeScript Best Practices for Large-Scale Applications",
    slug: "typescript-best-practices-large-scale-applications",
    excerpt:
      "Strict mode, parsing at the boundary, and modelling states so illegal combinations cannot be represented — TypeScript that prevents bugs instead of annotating them.",
    category: "TypeScript",
    tags: ["TypeScript", "Best Practices", "Architecture"],
    readTimeMinutes: 8,
    coverImage:
      "https://images.unsplash.com/photo-1516116216624-53e697fedbea?w=1200&h=630&fit=crop",
    publishedAt: new Date("2024-09-08"),
    published: true,
    featured: false,
    seoTitle: "TypeScript Best Practices for Large Codebases",
    seoDescription:
      "Strict mode, runtime validation at boundaries, discriminated unions and branded types — practical TypeScript patterns for large applications.",
    body: [
      "TypeScript pays off in proportion to how seriously you take it. A codebase full of `any` and casts has all the build cost of TypeScript and almost none of the benefit.",
      "",
      "## Turn strict on now",
      "",
      "`strict: true` from day one. Retrofitting it onto a large untyped codebase is genuinely painful, which is exactly why teams keep postponing it and never do it.",
      "",
      "The flag people disable first is `strictNullChecks`, and it is the one that catches the most real bugs. Keep it.",
      "",
      "## Types are not validation",
      "",
      "This is the mistake I see most often:",
      "",
      "```ts",
      "const user = await res.json() as User; // a lie, not a guarantee",
      "```",
      "",
      "That cast asserts a shape the compiler cannot verify. If the API changed last week, you now have a `User` that is not one, and the failure surfaces somewhere unrelated.",
      "",
      "Parse at every boundary instead — network responses, form input, environment variables, URL params, anything crossing into your program from outside. Use a schema validator and derive the static type from the schema so the two cannot drift apart.",
      "",
      "## Make illegal states unrepresentable",
      "",
      "Compare:",
      "",
      "```ts",
      "// Permits { loading: true, error: 'x', data: {...} } — meaningless.",
      "type State = { loading: boolean; error?: string; data?: Data };",
      "",
      "// Only valid combinations exist.",
      "type State =",
      "  | { status: 'idle' }",
      "  | { status: 'loading' }",
      "  | { status: 'error'; error: string }",
      "  | { status: 'success'; data: Data };",
      "```",
      "",
      "The second version deletes an entire category of bug, and narrowing on `status` gives you exhaustiveness checking for free. This single pattern is the highest-value thing in TypeScript.",
      "",
      "## Stop primitive-obsessing on IDs",
      "",
      "When `UserId` and `OrderId` are both `string`, nothing stops you passing one where the other belongs. Branded types close that hole cheaply:",
      "",
      "```ts",
      "type UserId = string & { readonly __brand: 'UserId' };",
      "```",
      "",
      "In a large codebase with many entity types, this catches a surprising number of real mistakes.",
      "",
      "## Use `unknown`, not `any`",
      "",
      "`any` switches off the compiler and the effect spreads silently through everything it touches. `unknown` says the same thing honestly and forces a check before use. When you genuinely do not know a type, `unknown` is almost always what you meant.",
      "",
      "## Keep it readable",
      "",
      "Type-level programming is fun and easy to overdo. A five-line conditional generic that nobody on the team can modify is a liability, not a flex. If a type needs a comment explaining what it does, consider whether a simpler type plus a runtime check would serve better.",
      "",
      "Good TypeScript reads like documentation. That is the bar.",
    ].join("\n"),
  },
  {
    title: "Effective Testing Strategies for Mobile Applications",
    slug: "effective-testing-strategies-for-mobile-applications",
    excerpt:
      "What to test, what to skip, and why device fragmentation, permissions and flaky network conditions deserve more attention than your unit test count.",
    category: "Testing",
    tags: ["Testing", "Quality Assurance", "Mobile"],
    readTimeMinutes: 10,
    coverImage:
      "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1200&h=630&fit=crop",
    publishedAt: new Date("2024-09-01"),
    published: true,
    featured: false,
    seoTitle: "Mobile App Testing Strategy That Catches Real Bugs",
    seoDescription:
      "A practical mobile testing approach: what to unit test, where integration tests pay off, and the device, permission and network cases that break apps in production.",
    body: [
      "Mobile testing advice usually fixates on coverage percentages. Coverage is a weak proxy. What matters is whether your tests catch the things that actually break apps in the wild — and on mobile, those are rarely pure logic bugs.",
      "",
      "## Where the value actually is",
      "",
      "Weight your effort roughly like this:",
      "",
      "- **Unit tests** for logic with real branching: pricing, validation, date handling, state machines. Fast, stable, worth it.",
      "- **Integration tests** for a screen plus its data layer with the network mocked. This is the sweet spot on mobile — highest bug-catching per unit of maintenance.",
      "- **End-to-end tests** for a handful of critical flows only: sign up, log in, purchase. They are slow and flaky, so keep the set small and treat every flake as a bug in the test.",
      "",
      "Testing that a component renders a prop is not testing. Delete those.",
      "",
      "## The failures unique to mobile",
      "",
      "These are what actually reach production, and none are caught by a typical unit suite:",
      "",
      "**Permissions.** Test every path: granted, denied, denied permanently, revoked while the app is backgrounded. That last one is the classic crash — the user turns off camera access in Settings, returns, and your code assumes it still has it.",
      "",
      "**Interruptions.** Calls, notifications, backgrounding mid-flow, the OS killing your process to reclaim memory. Test that state survives a background-and-restore.",
      "",
      "**Network reality.** Not just offline — *bad*. High latency, packet loss, and the worst case of all: a connection that accepts requests and never responds. Enable network throttling and check that timeouts fire and errors surface.",
      "",
      "**Device fragmentation.** Small screens, huge screens, notches, large system font sizes. Bumping the OS text size to maximum breaks more layouts than any other single test I run.",
      "",
      "## Test on cheap hardware",
      "",
      "The mid-range Android device is where performance problems and memory pressure appear first. A test suite that only ever runs on a simulator on a fast laptop will let real problems through unchallenged.",
      "",
      "## Automate the boring part",
      "",
      "Run unit and integration tests on every pull request. Run the end-to-end suite and a device matrix nightly, because they are too slow to gate every commit. If a test is flaky, fix it or delete it — a suite people ignore is worse than no suite, because it provides false confidence.",
      "",
      "## Then actually use the app",
      "",
      "No automated suite catches an animation that stutters, a tap target too small for a thumb, or a flow that is technically correct and genuinely confusing. Fifteen minutes of using your own app on a real device before every release catches things no assertion ever will.",
    ].join("\n"),
  },
];
