import type {
  AddOnInput,
  ExperienceInput,
  ServicePackageInput,
  SkillCategoryInput,
  TestimonialInput,
} from "../../src/schemas";

export const experiences: ExperienceInput[] = [
  {
    role: "Senior Frontend Developer",
    company: "Phyxle",
    companyUrl: "",
    location: "Colombo, Sri Lanka (Remote)",
    period: "July 2024 – Present",
    startDate: new Date("2024-07-01"),
    endDate: null,
    current: true,
    responsibilities: [
      "Design and develop high-performance mobile and web applications with a focus on user-centric UX/UI functionality",
      "Collaborate with design teams to craft intuitive, visually appealing, and seamless user experiences",
      "Conduct thorough testing to ensure quality assurance for secure, reliable, and high-performing applications",
      "Work with backend and web hosting teams for smooth API integration and robust software architecture",
    ],
    published: true,
    order: 0,
  },
  {
    role: "Founder & Lead Developer",
    company: "Nesture Labs (Own Startup)",
    companyUrl: "https://nesturelabs.com",
    location: "Colombo, Sri Lanka",
    period: "January 2022 – Present",
    startDate: new Date("2022-01-01"),
    endDate: null,
    current: true,
    responsibilities: [
      "Founded and built an IT solutions company specializing in web, mobile, and AI development services",
      "Led end-to-end project delivery for diverse clients across healthcare, e-commerce, and corporate sectors",
      "Managed full-stack development using modern technologies including React, Node.js, and cloud services",
      "Built strategic partnerships and grew the company from concept to a profitable service provider",
    ],
    published: true,
    order: 1,
  },
  {
    role: "Mobile Application Developer",
    company: "Space IT Labs",
    companyUrl: "",
    location: "Nottingham, England, United Kingdom (Remote)",
    period: "November 2022 – June 2024",
    startDate: new Date("2022-11-01"),
    endDate: new Date("2024-06-30"),
    current: false,
    responsibilities: [
      "Developed the Lifesaylor Affirmation mobile application, significantly impacting the healthcare sector",
      "Collaborated with UI/UX teams to deliver engaging and functional designs",
      "Conducted comprehensive testing to ensure functionality, performance, and security",
      "Supported backend development and API testing for seamless integration and robust architecture",
    ],
    published: true,
    order: 2,
  },
];

export const skillCategories: SkillCategoryInput[] = [
  {
    title: "Mobile App Development",
    icon: "Smartphone",
    skills: [
      "iOS App Development",
      "Android App Development",
      "React Native Expert",
      "Flutter Development",
    ],
    published: true,
    order: 0,
  },
  {
    title: "React & Frontend Development",
    icon: "Code2",
    skills: [
      "React Expert",
      "Next.js App Router",
      "TypeScript",
      "Modern JavaScript",
      "Responsive Design",
      "Tailwind CSS",
    ],
    published: true,
    order: 1,
  },
  {
    title: "Backend & Database",
    icon: "Database",
    skills: ["Node.js", "Python", "MongoDB", "API Integration", "Database Management", "SQL"],
    published: true,
    order: 2,
  },
  {
    title: "Cloud & DevOps",
    icon: "Cloud",
    skills: ["Vercel", "CI/CD", "Cloud Platforms", "Web Hosting", "Version Control"],
    published: true,
    order: 3,
  },
  {
    title: "Development Practices",
    icon: "GitBranch",
    skills: ["Agile", "Scrum", "OOP", "Testing", "Code Review"],
    published: true,
    order: 4,
  },
  {
    title: "Design & UX",
    icon: "Palette",
    skills: ["UI/UX Collaboration", "Responsive Design", "User Experience", "Prototyping"],
    published: true,
    order: 5,
  },
];

export const servicePackages: ServicePackageInput[] = [
  {
    name: "Starter",
    slug: "starter",
    price: "$999",
    priceValue: 999,
    currency: "USD",
    period: "one-time",
    description: "Perfect for small businesses and startups needing a professional web presence",
    features: [
      "Responsive landing page (up to 5 pages)",
      "Mobile-first design",
      "SEO optimization",
      "Contact form integration",
      "Social media links",
      "Fast loading speed",
      "2 rounds of revisions",
      "1 month support",
      "Source code included",
    ],
    deliveryTime: "7-10 days",
    icon: "Zap",
    gradient: "blue",
    highlighted: false,
    published: true,
    order: 0,
  },
  {
    name: "Professional",
    slug: "professional",
    price: "$2,499",
    priceValue: 2499,
    currency: "USD",
    period: "one-time",
    description:
      "Ideal for growing businesses requiring custom web applications with advanced features",
    features: [
      "Custom React web application",
      "Up to 15 pages/sections",
      "Advanced UI/UX design",
      "Database integration",
      "Admin dashboard",
      "API integration",
      "Authentication system",
      "Payment gateway setup",
      "3 rounds of revisions",
      "3 months support",
      "Training & documentation",
      "Source code + deployment",
    ],
    deliveryTime: "3-4 weeks",
    icon: "Sparkles",
    gradient: "gold",
    highlighted: true,
    published: true,
    order: 1,
  },
  {
    name: "Enterprise",
    slug: "enterprise",
    price: "$5,999",
    priceValue: 5999,
    currency: "USD",
    period: "one-time",
    description: "Comprehensive solution for businesses needing mobile apps and complex systems",
    features: [
      "iOS & Android mobile app",
      "Full-featured web platform",
      "React Native development",
      "Custom backend & APIs",
      "Real-time features",
      "AI/ML integration",
      "Advanced analytics dashboard",
      "Multi-user roles & permissions",
      "Cloud deployment (AWS/GCP)",
      "Push notifications",
      "Unlimited revisions",
      "6 months priority support",
      "Maintenance plan included",
      "App Store deployment",
      "Complete documentation",
    ],
    deliveryTime: "6-8 weeks",
    icon: "Crown",
    gradient: "purple",
    highlighted: false,
    published: true,
    order: 2,
  },
];

export const addOns: AddOnInput[] = [
  {
    title: "AI Chatbot Integration",
    price: "$499",
    description: "Smart AI assistant trained on your content",
    published: true,
    order: 0,
  },
  {
    title: "E-commerce Setup",
    price: "$799",
    description: "Complete online store with payment processing",
    published: true,
    order: 1,
  },
  {
    title: "Monthly Maintenance",
    price: "$299/mo",
    description: "Updates, security patches, and technical support",
    published: true,
    order: 2,
  },
  {
    title: "SEO Optimization",
    price: "$399",
    description: "Advanced SEO setup and Google ranking optimization",
    published: true,
    order: 3,
  },
];

/**
 * NOTE ON STRUCTURED DATA: every entry below is seeded with `verified: false`,
 * which keeps it out of Review / AggregateRating JSON-LD. Flip `verified` to
 * true in the admin panel only for testimonials you can evidence (a real
 * client, a real engagement). Marking up unverifiable reviews breaches Google's
 * review snippet policy and risks a manual action against the whole domain.
 */
export const testimonials: TestimonialInput[] = [
  {
    name: "Sarah Johnson",
    role: "Product Manager",
    company: "TechCorp",
    content:
      "Working with Charm was exceptional. His attention to detail and ability to transform complex requirements into elegant solutions is remarkable. The mobile app he developed exceeded our expectations.",
    avatar: "SJ",
    website: "https://techcorp.com",
    rating: 5,
    verified: false,
    published: true,
    order: 0,
  },
  {
    name: "Dr. Michael Chen",
    role: "CEO",
    company: "Space IT Labs",
    content:
      "Charm's work on the Lifesaylor Affirmation app has been transformative for our healthcare initiatives. His technical expertise combined with genuine understanding of user needs resulted in an app that is making a real difference in people's lives.",
    avatar: "MC",
    website: "https://spaceitlabs.com",
    rating: 5,
    verified: false,
    published: true,
    order: 1,
  },
  {
    name: "Emma Rodriguez",
    role: "Healthcare Director",
    company: "Wellness Plus",
    content:
      "The Lifesaylor app has made a significant impact on our patients' daily motivation. Charm's understanding of user needs and technical implementation is top-notch. Highly professional and delivers beyond expectations.",
    avatar: "ER",
    website: "https://wellnessplus.health",
    rating: 5,
    verified: false,
    published: true,
    order: 2,
  },
  {
    name: "David Thompson",
    role: "Founder",
    company: "StartupHub",
    content:
      "Charm's frontend development skills are exceptional. He consistently delivers pixel-perfect designs with smooth animations and excellent performance. A true professional who understands both design and development.",
    avatar: "DT",
    website: "https://startuphub.io",
    rating: 5,
    verified: false,
    published: true,
    order: 3,
  },
  {
    name: "Lisa Anderson",
    role: "Marketing Director",
    company: "Digital Ventures",
    content:
      "Outstanding work on our web platform. Charm's ability to understand business requirements and translate them into beautiful, functional interfaces is impressive. The results exceeded our ROI projections.",
    avatar: "LA",
    website: "https://digitalventures.com",
    rating: 5,
    verified: false,
    published: true,
    order: 4,
  },
  {
    name: "James Wilson",
    role: "CTO",
    company: "InnovateTech Solutions",
    content:
      "Charm's technical expertise and problem-solving skills are outstanding. He delivered our mobile app ahead of schedule with exceptional quality and performance. The code quality and architecture are exemplary.",
    avatar: "JW",
    website: "https://innovatetech.io",
    rating: 5,
    verified: false,
    published: true,
    order: 5,
  },
  {
    name: "Sophie Martinez",
    role: "Lead Designer",
    company: "CreativeStudio",
    content:
      "Working with Charm was a pleasure. He perfectly implemented our designs with pixel-perfect accuracy and added thoughtful animations that enhanced the user experience. True collaboration at its best.",
    avatar: "SM",
    website: "https://creativestudio.design",
    rating: 5,
    verified: false,
    published: true,
    order: 6,
  },
  {
    name: "Robert Kim",
    role: "Business Owner",
    company: "Kim's Retail Group",
    content:
      "Charm transformed our outdated website into a modern, fast, and beautiful platform. Our conversion rates improved by 40% after the redesign. Highly professional and great communication throughout.",
    avatar: "RK",
    website: "https://kimsretail.com",
    rating: 5,
    verified: false,
    published: true,
    order: 7,
  },
  {
    name: "Emily Foster",
    role: "Project Manager",
    company: "DigitalHub Agency",
    content:
      "Exceptional communication and delivery. Charm kept us updated throughout the project and was always available to discuss improvements. The final product exceeded expectations and our client was thrilled.",
    avatar: "EF",
    website: "https://digitalhub.agency",
    rating: 5,
    verified: false,
    published: true,
    order: 8,
  },
  {
    name: "Dr. Thomas Brown",
    role: "Healthcare Administrator",
    company: "MediCare Systems",
    content:
      "The applications Charm developed have revolutionized how we engage with our patients. His attention to healthcare-specific requirements and user experience is remarkable.",
    avatar: "TB",
    website: "https://medicare-systems.health",
    rating: 5,
    verified: false,
    published: true,
    order: 9,
  },
  {
    name: "Rachel Cooper",
    role: "Operations Manager",
    company: "RestaurantPro",
    content:
      "The restaurant management system Charm built has transformed our operations. Reduced costs by 30% and improved efficiency dramatically. Best investment we have made in technology.",
    avatar: "RC",
    website: "https://restaurantpro.com",
    rating: 5,
    verified: false,
    published: true,
    order: 10,
  },
  {
    name: "Antonio Rossi",
    role: "Director",
    company: "GlobalTech Italia",
    content:
      "Charm's work on our corporate website was exceptional. The multilingual support and modern design perfectly represent our brand internationally. Professional, timely, and excellent quality.",
    avatar: "AR",
    website: "https://globaltech.it",
    rating: 5,
    verified: false,
    published: true,
    order: 11,
  },
  {
    name: "Patricia Hughes",
    role: "Founder",
    company: "PetCare Connect",
    content:
      "The Perera's Paws platform exceeded our expectations. Charm understood our vision for connecting pet lovers with services and created a beautiful, functional solution that our users love.",
    avatar: "PH",
    website: "https://petcareconnect.com",
    rating: 5,
    verified: false,
    published: true,
    order: 12,
  },
  {
    name: "Kevin Zhang",
    role: "CEO",
    company: "Analytics Pro",
    content:
      "The AI-powered analytics dashboard Charm developed has become central to our business operations. The insights and automation have helped us increase client ROI by 45%. Outstanding work.",
    avatar: "KZ",
    website: "https://analyticspro.io",
    rating: 5,
    verified: false,
    published: true,
    order: 13,
  },
  {
    name: "Maria Santos",
    role: "Director",
    company: "EduLearn Platform",
    content:
      "Our online learning platform built by Charm has scaled to thousands of students. The video streaming, live classes, and certificate system work flawlessly. Highly recommended for educational projects.",
    avatar: "MS",
    website: "https://edulearn.com",
    rating: 5,
    verified: false,
    published: true,
    order: 14,
  },
];
