import type { ProjectInput } from "../../src/schemas";

/**
 * Migrated verbatim from the previous Vite site's hard-coded `Projects.tsx`
 * array, plus the fields the new /projects/[slug] pages need (slug, body,
 * category, SEO overrides).
 *
 * REVIEW BEFORE LAUNCH: several `liveUrl` values point at *.nesturelabs.com
 * demo subdomains. Any that do not resolve become broken outbound links, which
 * hurts both crawl budget and visitor trust. Clear the URL in the admin panel
 * for anything that is not actually live.
 */
export const projects: ProjectInput[] = [
  {
    title: "Lifesaylor",
    slug: "lifesaylor",
    description:
      "A daily motivation mobile app designed to inspire users through meaningful quotes and affirmations. Successfully launched on Google Play Store with significant impact in the healthcare sector.",
    fullDescription:
      "Lifesaylor is a comprehensive mobile application that delivers daily motivation through carefully curated quotes, affirmations, and mindfulness exercises. The app features a beautiful, intuitive interface with smooth animations and personalized content delivery. Successfully launched on Google Play Store, it has helped thousands of users in the healthcare sector maintain positive mental health and daily motivation.",
    body: [
      "## Overview",
      "",
      "Lifesaylor delivers daily motivation through curated quotes, affirmations and short mindfulness exercises. It was built for a healthcare audience, where consistency matters more than novelty, so the whole product is designed around a single daily touchpoint that people actually return to.",
      "",
      "## What I built",
      "",
      "- A cross-platform mobile client with a content feed tuned for fast first paint on low-end Android devices",
      "- Customisable notification scheduling, so users pick the moment that fits their routine",
      "- A favourites collection with offline access, backed by local persistence",
      "- Progress tracking that visualises streaks without turning wellbeing into a leaderboard",
      "",
      "## Technical notes",
      "",
      "Content is delivered from a lightweight API with aggressive client-side caching, so the app opens instantly and syncs in the background. Notification scheduling runs entirely on-device to avoid depending on push infrastructure for the core loop.",
      "",
      "## Outcome",
      "",
      "Shipped to the Google Play Store and adopted across healthcare settings, where it supports patients and staff in maintaining daily motivation.",
    ].join("\n"),
    technologies: ["Mobile App", "Android", "iOS", "React Native", "Healthcare"],
    coverImage: "",
    liveUrl: "https://play.google.com/store/apps/details?id=com.lifesaylor",
    repoUrl: "",
    client: "Space IT Labs",
    category: "Mobile",
    featured: true,
    published: true,
    order: 0,
    completedAt: new Date("2023-08-01"),
    seoTitle: "Lifesaylor — Daily Motivation Mobile App Case Study",
    seoDescription:
      "How I built Lifesaylor, a daily motivation and affirmation mobile app for the healthcare sector, shipped on Google Play.",
  },
  {
    title: "Lifesaylor Affirmation",
    slug: "lifesaylor-affirmation",
    // Content replaced 2026-09 with verified Play Store listing data supplied
    // directly by the user — including a corrected liveUrl package ID
    // (previously com.lifesaylor.affirmation). The prior voice-recording /
    // background-audio description was superseded, not merged, since the
    // verified listing describes a curated affirmation library instead.
    description:
      "A companion app to Lifesaylor focused on daily affirmations across self-love, success, gratitude, and stress relief, helping users build a consistent positive-thinking practice.",
    fullDescription:
      "A companion app to Lifesaylor focused on daily affirmations across self-love, success, gratitude, and stress relief, helping users build a consistent positive-thinking practice.",
    body: [
      "## Overview",
      "",
      "A companion app to Lifesaylor focused on daily affirmations across self-love, success, gratitude, and stress relief, helping users build a consistent positive-thinking practice.",
      "",
      "## What I built",
      "",
      "- A curated affirmation library organized by life area (self-love, success, gratitude, stress relief)",
      "- A simple, distraction-free interface for daily affirmation browsing",
      "",
      "## Outcome",
      "",
      "Published to the Google Play Store with a 4.9-star rating across 15 reviews.",
    ].join("\n"),
    technologies: ["React Native", "Android", "iOS"],
    coverImage: "",
    liveUrl: "https://play.google.com/store/apps/details?id=life.saylor.affirmation",
    repoUrl: "",
    client: "Space IT Labs",
    category: "Mobile",
    featured: true,
    published: true,
    order: 1,
    completedAt: new Date("2024-02-01"),
    seoTitle: "Lifesaylor Affirmation — Daily Affirmations App Case Study",
    seoDescription:
      "A companion app to Lifesaylor delivering daily affirmations across self-love, success, gratitude, and stress relief.",
  },
  {
    title: "E-Commerce Platform",
    slug: "ecommerce-platform",
    description:
      "A modern e-commerce solution with real-time inventory management, secure payment processing, and advanced analytics dashboard.",
    fullDescription:
      "A full-featured e-commerce platform with a seamless shopping experience, integrated payment gateways including Stripe and PayPal, real-time order tracking, and a comprehensive admin dashboard. Features include product recommendations, wishlist functionality, and automated email notifications.",
    body: [
      "## Overview",
      "",
      "A full-stack commerce platform covering the whole path from catalogue browsing to fulfilment, with an operator dashboard for the team running it day to day.",
      "",
      "## Storefront",
      "",
      "- Server-rendered product and category pages for search visibility",
      "- Real-time stock levels so customers never buy something that just sold out",
      "- Wishlists and recommendation surfaces driven by browsing history",
      "",
      "## Payments and fulfilment",
      "",
      "Stripe and PayPal integration with webhook-driven order state, so payment confirmation is authoritative on the server rather than trusted from the client. Order tracking and automated transactional email cover the post-purchase journey.",
      "",
      "## Admin",
      "",
      "A dashboard covering inventory, orders, refunds and revenue reporting, built so non-technical staff can run the store without developer involvement.",
    ].join("\n"),
    technologies: ["React", "Node.js", "MongoDB", "Stripe API"],
    coverImage: "",
    liveUrl: "",
    repoUrl: "",
    client: "",
    category: "Web",
    featured: true,
    published: true,
    order: 2,
    completedAt: null,
    seoTitle: "E-Commerce Platform Case Study — React, Node.js & Stripe",
    seoDescription:
      "A custom e-commerce build with real-time inventory, Stripe and PayPal payments, and a full operations dashboard.",
  },
  {
    title: "Healthcare Management System",
    slug: "healthcare-management-system",
    description:
      "Comprehensive patient management system with appointment scheduling, medical records, and telemedicine capabilities.",
    fullDescription:
      "A healthcare platform that streamlines clinic operations. Features include a patient portal, doctor dashboards, appointment scheduling, prescription management, video consultations, and integrated billing.",
    body: [
      "## Overview",
      "",
      "A clinic operations platform bringing scheduling, records, consultations and billing into one system, replacing a mix of paper and spreadsheets.",
      "",
      "## Modules",
      "",
      "- **Patient portal** — booking, history, and documents",
      "- **Clinician dashboard** — daily schedule, notes, prescriptions",
      "- **Telemedicine** — WebRTC video consultations with in-call notes",
      "- **Billing** — invoicing tied to appointments and procedures",
      "",
      "## Handling sensitive data",
      "",
      "Health records demand strict access control. The system uses role-based permissions with an audit trail on every record access, encrypted storage for documents, and session policies appropriate to shared clinic workstations.",
    ].join("\n"),
    technologies: ["React", "TypeScript", "PostgreSQL", "WebRTC"],
    coverImage: "",
    liveUrl: "",
    repoUrl: "",
    client: "",
    category: "Web",
    featured: true,
    published: true,
    order: 3,
    completedAt: null,
    seoTitle: "Healthcare Management System Case Study",
    seoDescription:
      "A patient management platform with scheduling, records, WebRTC telemedicine and billing, built with React and TypeScript.",
  },
  {
    title: "AI-Powered Analytics Dashboard",
    slug: "ai-analytics-dashboard",
    description:
      "Business intelligence platform with machine learning insights, predictive analytics, and automated reporting.",
    fullDescription:
      "An enterprise analytics solution that processes large data volumes to deliver actionable insights. Features AI-powered trend detection, custom report generation, real-time data visualization, and automated alerts.",
    body: [
      "## Overview",
      "",
      "A business intelligence surface that turns raw event data into decisions: trend detection, forecasting, and alerting when metrics move outside expected bounds.",
      "",
      "## Capabilities",
      "",
      "- Real-time dashboards built on D3 for visualisations off the shelf charting could not express",
      "- Trend and anomaly detection over historical series",
      "- Custom report builder with scheduled delivery",
      "- Threshold and anomaly alerts routed to email and chat",
      "",
      "## Performance",
      "",
      "The interesting constraint was rendering large series without freezing the browser. Aggregation happens server-side at query time, with the client receiving downsampled series sized to the viewport, so charts stay responsive regardless of the underlying row count.",
    ].join("\n"),
    technologies: ["React", "Python", "TensorFlow", "D3.js"],
    coverImage: "",
    liveUrl: "",
    repoUrl: "",
    client: "",
    category: "AI",
    featured: true,
    published: true,
    order: 4,
    completedAt: null,
    seoTitle: "AI Analytics Dashboard Case Study — React, Python & D3",
    seoDescription:
      "Building a business intelligence dashboard with anomaly detection, forecasting and large-series visualisation.",
  },
  {
    title: "Restaurant Management Suite",
    slug: "restaurant-management-suite",
    description:
      "All-in-one restaurant solution with POS, inventory, delivery tracking, and customer loyalty programs.",
    fullDescription:
      "A complete restaurant management ecosystem handling orders, kitchen operations, staff management, and customer engagement. Integrated with delivery platforms, payment processors, and accounting software.",
    body: [
      "## Overview",
      "",
      "An operations suite for restaurants: point of sale, kitchen display, inventory, delivery and loyalty, designed to run on cheap tablet hardware in a hot, busy kitchen.",
      "",
      "## Modules",
      "",
      "- **POS** — fast order entry with modifiers and split billing",
      "- **Kitchen display** — live ticket queue with prep timing",
      "- **Inventory** — stock deduction per sale with low-stock alerts",
      "- **Delivery** — dispatch and tracking, integrated with third-party platforms",
      "- **Loyalty** — points and repeat-customer campaigns",
      "",
      "## Offline first",
      "",
      "Restaurant Wi-Fi fails at exactly the wrong moment. Order entry writes to a local queue and syncs when connectivity returns, so service continues through network drops and nothing is lost.",
    ].join("\n"),
    technologies: ["React Native", "Node.js", "Firebase", "Stripe"],
    coverImage: "",
    liveUrl: "",
    repoUrl: "",
    client: "",
    category: "Mobile",
    featured: true,
    published: true,
    order: 5,
    completedAt: null,
    seoTitle: "Restaurant Management Suite Case Study",
    seoDescription:
      "An offline-first POS, kitchen display, inventory and delivery suite built with React Native and Firebase.",
  },
  {
    title: "Perera's Paws",
    slug: "pereras-paws",
    description:
      "A pet care and adoption platform connecting pet lovers with shelters and services. Professional website with modern design and user-friendly interface.",
    fullDescription: "",
    body: "",
    technologies: ["Web App", "React", "Frontend"],
    coverImage: "",
    liveUrl: "https://pereras-paws.com",
    repoUrl: "",
    client: "",
    category: "Web",
    featured: false,
    published: true,
    order: 6,
    completedAt: null,
    seoTitle: "",
    seoDescription: "",
  },
  {
    title: "Charm Thiekshana Portfolio",
    slug: "charm-thiekshana-portfolio",
    description:
      "A personal portfolio website highlighting professional achievements, projects, and skills. Built with modern technologies and responsive design.",
    fullDescription: "",
    body: "",
    technologies: ["Portfolio", "React", "Responsive"],
    coverImage: "",
    liveUrl: "https://www.charmthiekshana.com",
    repoUrl: "",
    client: "",
    category: "Web",
    featured: false,
    published: true,
    order: 7,
    completedAt: null,
    seoTitle: "",
    seoDescription: "",
  },
  {
    title: "Nesture Labs",
    slug: "nesture-labs",
    description:
      "The official website for my IT solutions startup offering web, mobile, and AI development services. Comprehensive platform showcasing technical capabilities.",
    fullDescription: "",
    body: "",
    technologies: ["Corporate", "IT Solutions", "Full Stack"],
    coverImage: "",
    liveUrl: "https://nesturelabs.com",
    repoUrl: "",
    client: "",
    category: "Web",
    featured: false,
    published: true,
    order: 8,
    completedAt: null,
    seoTitle: "",
    seoDescription: "",
  },
  {
    title: "Real Estate Portal",
    slug: "real-estate-portal",
    description:
      "A property listing platform with advanced search filters, virtual tours, mortgage calculator, and integrated booking system.",
    fullDescription: "",
    body: "",
    technologies: ["Next.js", "Tailwind CSS", "Map Integration"],
    coverImage: "",
    liveUrl: "",
    repoUrl: "",
    client: "",
    category: "Web",
    featured: false,
    published: true,
    order: 9,
    completedAt: null,
    seoTitle: "",
    seoDescription: "",
  },
  {
    title: "Fitness Tracker App",
    slug: "fitness-tracker-app",
    description:
      "A comprehensive fitness application with workout plans, nutrition tracking, progress analytics, and social features for fitness enthusiasts.",
    fullDescription: "",
    body: "",
    technologies: ["React Native", "Firebase", "HealthKit"],
    coverImage: "",
    liveUrl: "",
    repoUrl: "",
    client: "",
    category: "Mobile",
    featured: false,
    published: true,
    order: 10,
    completedAt: null,
    seoTitle: "",
    seoDescription: "",
  },
  {
    title: "Social Media Management Tool",
    slug: "social-media-management-tool",
    description:
      "Multi-platform social media scheduler with analytics, content calendar, and team collaboration features for businesses.",
    fullDescription: "",
    body: "",
    technologies: ["React", "Redux", "GraphQL", "AWS"],
    coverImage: "",
    liveUrl: "",
    repoUrl: "",
    client: "",
    category: "Web",
    featured: false,
    published: true,
    order: 11,
    completedAt: null,
    seoTitle: "",
    seoDescription: "",
  },
  {
    title: "Online Learning Platform",
    slug: "online-learning-platform",
    description:
      "Educational platform with video courses, live classes, assignments, progress tracking, and certification system.",
    fullDescription: "",
    body: "",
    technologies: ["React", "WebRTC", "MongoDB", "AWS S3"],
    coverImage: "",
    liveUrl: "",
    repoUrl: "",
    client: "",
    category: "Web",
    featured: false,
    published: true,
    order: 12,
    completedAt: null,
    seoTitle: "",
    seoDescription: "",
  },
  {
    title: "Event Management System",
    slug: "event-management-system",
    description:
      "Complete event planning solution with ticketing, attendee management, check-in system, and real-time analytics.",
    fullDescription: "",
    body: "",
    technologies: ["React", "Node.js", "QR Code", "Payment Gateway"],
    coverImage: "",
    liveUrl: "",
    repoUrl: "",
    client: "",
    category: "Web",
    featured: false,
    published: true,
    order: 13,
    completedAt: null,
    seoTitle: "",
    seoDescription: "",
  },
  {
    title: "Hotel Booking Platform",
    slug: "hotel-booking-platform",
    description:
      "Hotel reservation system with availability calendar, pricing engine, payment processing, and guest management features.",
    fullDescription: "",
    body: "",
    technologies: ["Next.js", "Prisma", "Stripe", "AWS"],
    coverImage: "",
    liveUrl: "",
    repoUrl: "",
    client: "",
    category: "Web",
    featured: false,
    published: true,
    order: 14,
    completedAt: null,
    seoTitle: "",
    seoDescription: "",
  },
  {
    title: "Inventory Management System",
    slug: "inventory-management-system",
    description:
      "Advanced inventory tracking with barcode scanning, automated reordering, supplier management, and multi-location support.",
    fullDescription: "",
    body: "",
    technologies: ["React", "Node.js", "PostgreSQL", "Redis"],
    coverImage: "",
    liveUrl: "",
    repoUrl: "",
    client: "",
    category: "Web",
    featured: false,
    published: true,
    order: 15,
    completedAt: null,
    seoTitle: "",
    seoDescription: "",
  },
  {
    title: "Delivery Tracking App",
    slug: "delivery-tracking-app",
    description:
      "Real-time delivery tracking system with driver management, route optimization, and customer notifications.",
    fullDescription: "",
    body: "",
    technologies: ["React Native", "Google Maps", "Socket.io", "Node.js"],
    coverImage: "",
    liveUrl: "",
    repoUrl: "",
    client: "",
    category: "Mobile",
    featured: false,
    published: true,
    order: 16,
    completedAt: null,
    seoTitle: "",
    seoDescription: "",
  },
  {
    title: "CRM System",
    slug: "crm-system",
    description:
      "Customer relationship management platform with lead tracking, pipeline management, email campaigns, and reporting.",
    fullDescription: "",
    body: "",
    technologies: ["React", "TypeScript", "PostgreSQL", "SendGrid"],
    coverImage: "",
    liveUrl: "",
    repoUrl: "",
    client: "",
    category: "Web",
    featured: false,
    published: true,
    order: 17,
    completedAt: null,
    seoTitle: "",
    seoDescription: "",
  },
  {
    title: "Appointment Booking System",
    slug: "appointment-booking-system",
    description:
      "Flexible scheduling solution for service businesses with calendar sync, reminders, and payment integration.",
    fullDescription: "",
    body: "",
    technologies: ["React", "Node.js", "Calendar Sync", "Stripe"],
    coverImage: "",
    liveUrl: "",
    repoUrl: "",
    client: "",
    category: "Web",
    featured: false,
    published: true,
    order: 18,
    completedAt: null,
    seoTitle: "",
    seoDescription: "",
  },
  {
    title: "Financial Dashboard",
    slug: "financial-dashboard",
    description:
      "Personal finance tracking with budget management, expense categorization, investment tracking, and financial goals.",
    fullDescription: "",
    body: "",
    technologies: ["React", "Chart.js", "Plaid API", "Firebase"],
    coverImage: "",
    liveUrl: "",
    repoUrl: "",
    client: "",
    category: "Web",
    featured: false,
    published: true,
    order: 19,
    completedAt: null,
    seoTitle: "",
    seoDescription: "",
  },

  // ---------------------------------------------------------------------
  // The 8 entries below are drafts (published: false) added ahead of their
  // real case-study content. Every "description"/"body" field is a literal
  // [TODO] placeholder — none of it is fabricated. `completedAt` is only an
  // approximate month, derived from file timestamps, not a confirmed launch
  // date; category/title are best-effort guesses from the domain name and
  // are flagged inline where the guess is a stretch. Fill in real content
  // via /admin/projects, then flip `published` to true when ready.
  // ---------------------------------------------------------------------
  {
    title: "Lanka Pass Travel",
    slug: "lanka-pass-travel",
    description: "[TODO: short one-line summary]",
    fullDescription: "[TODO: describe what you actually built here]",
    body: [
      "## Overview",
      "",
      "[TODO: describe what you actually built here]",
      "",
      "## What I built",
      "",
      "[TODO: describe what you actually built here]",
      "",
      "## Technical notes",
      "",
      "[TODO: describe what you actually built here]",
      "",
      "## Outcome",
      "",
      "[TODO: describe what you actually built here]",
    ].join("\n"),
    technologies: ["Static Site"],
    coverImage: "",
    liveUrl: "https://lankapasstravel.com",
    repoUrl: "",
    client: "[CLIENT NAME]",
    // Guess from the domain name ("travel") — confirm or correct.
    category: "Travel",
    featured: false,
    published: false,
    order: 20,
    completedAt: new Date("2026-08-01"), // ~Aug 2026, approximate (file timestamp)
    seoTitle: "",
    seoDescription: "",
  },
  {
    title: "Lynk Facility",
    slug: "lynk-facility",
    description: "[TODO: short one-line summary]",
    fullDescription: "[TODO: describe what you actually built here]",
    body: [
      "## Overview",
      "",
      "[TODO: describe what you actually built here]",
      "",
      "## What I built",
      "",
      "[TODO: describe what you actually built here]",
      "",
      "## Technical notes",
      "",
      "[TODO: describe what you actually built here]",
      "",
      "## Outcome",
      "",
      "[TODO: describe what you actually built here]",
    ].join("\n"),
    technologies: ["Static Site"],
    coverImage: "",
    liveUrl: "https://lynkfacility.com.au",
    repoUrl: "",
    client: "[CLIENT NAME]",
    // Guess from the domain name ("facility") — confirm or correct.
    category: "Business Site",
    featured: false,
    published: false,
    order: 21,
    completedAt: new Date("2025-12-01"), // ~Dec 2025, approximate (file timestamp)
    seoTitle: "",
    seoDescription: "",
  },
  {
    title: "Amazon College",
    slug: "amazon-college",
    description: "[TODO: short one-line summary]",
    fullDescription: "[TODO: describe what you actually built here]",
    body: [
      "## Overview",
      "",
      "[TODO: describe what you actually built here]",
      "",
      "## What I built",
      "",
      "[TODO: describe what you actually built here]",
      "",
      "## Technical notes",
      "",
      // Flagged so the shared-docroot detail isn't lost before you write this up.
      "[TODO: describe what you actually built here — note: shares a docroot with amazon.phyxle.com.au]",
      "",
      "## Outcome",
      "",
      "[TODO: describe what you actually built here]",
    ].join("\n"),
    technologies: ["Static Site"],
    coverImage: "",
    liveUrl: "https://amazoncollege.lk",
    repoUrl: "",
    client: "[CLIENT NAME]",
    // "College" in the name — reasonably confident this is Education.
    category: "Education",
    featured: false,
    published: false,
    order: 22,
    completedAt: new Date("2026-04-01"), // ~Apr 2026, approximate (file timestamp)
    seoTitle: "",
    seoDescription: "",
  },
  {
    title: "Christech",
    slug: "christech",
    description: "[TODO: short one-line summary]",
    fullDescription: "[TODO: describe what you actually built here]",
    body: [
      "## Overview",
      "",
      "[TODO: describe what you actually built here]",
      "",
      "## What I built",
      "",
      "[TODO: describe what you actually built here]",
      "",
      "## Technical notes",
      "",
      "[TODO: describe what you actually built here — has a legacy PHP backend]",
      "",
      "## Outcome",
      "",
      "[TODO: describe what you actually built here]",
    ].join("\n"),
    technologies: ["Static Site", "PHP"],
    coverImage: "",
    liveUrl: "https://christech.lk",
    repoUrl: "",
    client: "[CLIENT NAME]",
    // No confident signal from the name — generic placeholder, please correct.
    category: "Business Site",
    featured: false,
    published: false,
    order: 23,
    completedAt: new Date("2022-02-01"), // ~Feb 2022, approximate (file timestamp) — the oldest of this batch
    seoTitle: "",
    seoDescription: "",
  },
  {
    title: "HigenIQ",
    slug: "higeniq",
    description: "[TODO: short one-line summary]",
    fullDescription: "[TODO: describe what you actually built here]",
    body: [
      "## Overview",
      "",
      "[TODO: describe what you actually built here]",
      "",
      "## What I built",
      "",
      "[TODO: describe what you actually built here]",
      "",
      "## Technical notes",
      "",
      "[TODO: describe what you actually built here — largest site of this batch, PHP backend]",
      "",
      "## Outcome",
      "",
      "[TODO: describe what you actually built here]",
    ].join("\n"),
    technologies: ["Static Site", "PHP"],
    coverImage: "",
    liveUrl: "https://higeniq.phyxle.com.au",
    repoUrl: "",
    client: "[CLIENT NAME]",
    // No confident signal from the name — generic placeholder, please correct.
    category: "Business Site",
    featured: false,
    published: false,
    order: 24,
    completedAt: new Date("2026-03-01"), // ~Mar 2026, approximate (file timestamp)
    seoTitle: "",
    seoDescription: "",
  },
  {
    title: "Lynk Facility Onboarding",
    slug: "lynk-facility-onboarding",
    description: "[TODO: short one-line summary]",
    fullDescription: "[TODO: describe what you actually built here]",
    body: [
      "## Overview",
      "",
      "[TODO: describe what you actually built here]",
      "",
      "## What I built",
      "",
      "[TODO: describe what you actually built here]",
      "",
      "## Technical notes",
      "",
      "[TODO: describe what you actually built here — Node.js + PHP backend]",
      "",
      "## Outcome",
      "",
      "[TODO: describe what you actually built here]",
    ].join("\n"),
    technologies: ["Static Site", "Node.js", "PHP"],
    coverImage: "",
    liveUrl: "https://onboarding.lynkfacility.com.au",
    repoUrl: "",
    client: "[CLIENT NAME]",
    // Subdomain of Lynk Facility — likely an internal onboarding tool/portal.
    category: "Web App",
    featured: false,
    published: false,
    order: 25,
    completedAt: new Date("2023-01-01"), // ~Jan 2023, approximate (file timestamp)
    seoTitle: "",
    seoDescription: "",
  },
  {
    title: "Aerotek",
    slug: "aerotek",
    description: "[TODO: short one-line summary]",
    fullDescription: "[TODO: describe what you actually built here]",
    body: [
      "## Overview",
      "",
      "[TODO: describe what you actually built here]",
      "",
      "## What I built",
      "",
      "[TODO: describe what you actually built here]",
      "",
      "## Technical notes",
      "",
      "[TODO: describe what you actually built here — separate PHP api/ backend]",
      "",
      "## Outcome",
      "",
      "[TODO: describe what you actually built here]",
    ].join("\n"),
    technologies: ["Static Site", "PHP", "API"],
    coverImage: "",
    liveUrl: "https://aerotek.lk",
    repoUrl: "",
    client: "[CLIENT NAME]",
    // No confident signal from the name — generic placeholder, please correct.
    category: "Business Site",
    featured: false,
    published: false,
    order: 26,
    completedAt: new Date("2026-02-01"), // ~Feb 2026, approximate (file timestamp)
    seoTitle: "",
    seoDescription: "",
  },
  {
    title: "Cleany Glow",
    slug: "cleanyglow",
    description: "[TODO: short one-line summary]",
    fullDescription: "[TODO: describe what you actually built here]",
    body: [
      "## Overview",
      "",
      "[TODO: describe what you actually built here]",
      "",
      "## What I built",
      "",
      "[TODO: describe what you actually built here]",
      "",
      "## Technical notes",
      "",
      // Backend tech for this one wasn't specified — do not guess it.
      "[TODO: describe what you actually built here — has a backend subfolder, stack to confirm]",
      "",
      "## Outcome",
      "",
      "[TODO: describe what you actually built here]",
    ].join("\n"),
    technologies: ["Static Site"],
    coverImage: "",
    liveUrl: "https://cleanyglow.com.au",
    repoUrl: "",
    client: "[CLIENT NAME]",
    // Guess from the name ("cleany") — confirm or correct.
    category: "Business Site",
    featured: false,
    published: false,
    order: 27,
    completedAt: new Date("2026-03-01"), // ~Mar 2026, approximate (file timestamp)
    seoTitle: "",
    seoDescription: "",
  },

  // ---------------------------------------------------------------------
  // Fully detailed, ready to publish — verified Play Store listing data.
  // ---------------------------------------------------------------------
  {
    title: "Quiet",
    slug: "quiet",
    description:
      "A minimalist Android home-screen launcher built around intentional phone use — replacing app icons and notification clutter with a clean, text-only interface.",
    fullDescription:
      "A minimalist Android home-screen launcher built around intentional phone use — replacing app icons and notification clutter with a clean, text-only interface.",
    body: [
      "## Overview",
      "",
      "A minimalist Android home-screen launcher built around intentional phone use — replacing app icons and notification clutter with a clean, text-only interface.",
      "",
      "## What I built",
      "",
      "- A text-only home screen replacement with a large clock/date display",
      "- Up to 20 pinned favourite apps as text labels, organized into folders",
      "- Full app list on swipe-up with instant search, filtering, and sorting",
      "- Sticky notes with optional reminder notifications",
      "- Countdown timers, a to-do list, and daily habit tracking on the home screen",
      "- On-device 7-day stats view for habit/to-do completion (no data uploaded)",
      "- Focus mode with a distraction pause before opening flagged apps",
      "- Biometric app-locking, daily unlock count, screen-time awareness",
      "- 7 themes including true AMOLED black",
      "- Full backup/restore as a single file",
      "",
      "## Technical notes",
      "",
      "Fully on-device — no analytics, ads, or tracking. The only optional network call is for the weather line, which is off by default.",
      "",
      "## Outcome",
      "",
      "Published to the Google Play Store under Nesture Labs.",
    ].join("\n"),
    // Stack not yet confirmed — do not guess Kotlin/Java/Flutter for an Android launcher.
    technologies: ["[CONFIRM STACK]"],
    coverImage: "",
    liveUrl: "https://play.google.com/store/apps/details?id=com.nexturelabs.quiet",
    repoUrl: "",
    // Personal project under Charm's own company, not client work — the schema
    // has no dedicated field for that distinction, so it's noted in `client`.
    client: "Nesture Labs (own project — founder: Charm Thiekshana Perera)",
    // Set to plain "Mobile" (not "Mobile / Productivity" as given) so it
    // exact-matches Lifesaylor/Lifesaylor Affirmation's category — "related
    // projects" is a strict string match, so this is what makes the three
    // mobile apps actually cross-link to each other.
    category: "Mobile",
    featured: false,
    published: true,
    order: 28,
    completedAt: new Date("2026-08-01"), // ~Aug 2026, last store update date
    seoTitle: "Quiet — Minimalist Android Launcher Case Study",
    seoDescription:
      "Quiet is a minimalist, fully on-device Android launcher for intentional phone use — no ads, no tracking, no analytics.",
  },

  // ---------------------------------------------------------------------
  // Verified via live fetch of each site (meta author/designer/developer
  // tags where noted) — draft (published: false) until the flagged open
  // items below are confirmed: tech stack, and for #14/#15/#16 the
  // client-vs-personal / real-name-vs-anonymized decisions.
  // ---------------------------------------------------------------------
  {
    title: "FBV Down",
    slug: "fbv-down",
    description:
      "A free online tool for downloading Facebook videos in HD or SD quality, no login or software required.",
    fullDescription:
      "A free online tool for downloading Facebook videos in HD or SD quality, no login or software required.",
    body: [
      "## Overview",
      "",
      "A free online tool for downloading Facebook videos in HD or SD quality, no login or software required.",
    ].join("\n"),
    // Stack not yet confirmed — do not guess.
    technologies: ["[CONFIRM STACK]"],
    coverImage: "",
    liveUrl: "https://www.fbvdown.com",
    repoUrl: "",
    // Own project, not client work — confirmed via the site's own meta author tag.
    client: "Own project (not client work)",
    category: "Web / Tool",
    featured: false,
    published: false,
    order: 29,
    completedAt: null, // no build date confirmed — do not invent one
    seoTitle: "",
    seoDescription: "",
  },
  {
    title: "Austin House",
    slug: "austin-house",
    description:
      "Website for Austin House, an aesthetic and beauty centre in Colombo offering facials, laser treatments, manicures, and wellness services.",
    fullDescription:
      "Website for Austin House, an aesthetic and beauty centre in Colombo offering facials, laser treatments, manicures, and wellness services. Also available at austinhouse.com.lk.",
    body: [
      "## Overview",
      "",
      "Website for Austin House, an aesthetic and beauty centre in Colombo offering facials, laser treatments, manicures, and wellness services. Also available at austinhouse.com.lk.",
    ].join("\n"),
    // Stack not yet confirmed — do not guess.
    technologies: ["[CONFIRM STACK]"],
    coverImage: "",
    liveUrl: "https://austinhouse.lk",
    repoUrl: "",
    client: "Austin House Aesthetic Centre",
    category: "Web / Business site",
    featured: false,
    published: false,
    order: 30,
    completedAt: null,
    seoTitle: "",
    seoDescription: "",
  },
  {
    title: "Tech Agent Labs",
    slug: "tech-agent-labs",
    description:
      "A marketplace and custom-development studio for production-ready AI agents — plug-and-play automation bots for sales, support, and business operations.",
    fullDescription:
      "A marketplace and custom-development studio for production-ready AI agents — plug-and-play automation bots for sales, support, and business operations.",
    body: [
      "## Overview",
      "",
      "A marketplace and custom-development studio for production-ready AI agents — plug-and-play automation bots for sales, support, and business operations.",
    ].join("\n"),
    // Stack not yet confirmed — do not guess.
    technologies: ["[CONFIRM STACK]"],
    coverImage: "",
    liveUrl: "https://techagentlabs.com",
    repoUrl: "",
    // No authorship meta-tag confirmation available for this one — client vs
    // personal project is unresolved, unlike FBV Down/Austin House above.
    client: "[CONFIRM: client project or personal/own project]",
    category: "Web / SaaS marketplace",
    featured: false,
    published: false,
    order: 31,
    completedAt: null,
    seoTitle: "",
    seoDescription: "",
  },
  {
    title: "Kavini & Nuwan Wedding Invitation",
    slug: "kavini-nuwan-wedding-invitation",
    description:
      "A digital wedding invitation for Kavini & Nuwan, featuring RSVP collection via WhatsApp, event countdown, embedded map/calendar integration, and a couple's-story section.",
    fullDescription:
      "A digital wedding invitation for Kavini & Nuwan, featuring RSVP collection via WhatsApp, event countdown, embedded map/calendar integration, and a couple's-story section.",
    body: [
      "## Overview",
      "",
      "A digital wedding invitation for Kavini & Nuwan, featuring RSVP collection via WhatsApp, event countdown, embedded map/calendar integration, and a couple's-story section.",
    ].join("\n"),
    // Next.js/Vercel confirmed by hosting; any other stack pieces unconfirmed.
    technologies: ["Next.js", "Vercel", "[CONFIRM any others]"],
    coverImage: "",
    liveUrl: "https://kavini-nuwan-wedding.vercel.app",
    repoUrl: "",
    // Real vs. anonymized naming for a private client is unresolved — using
    // the given names as a working placeholder until confirmed.
    client: "Kavini & Nuwan [CONFIRM: real names OK, or anonymize to \"Private client\"?]",
    // Same category string as the Homecoming Reception entry below, on
    // purpose — "related projects" is an exact category match, so this is
    // what makes the two companion sites cross-link to each other.
    category: "Web / Event",
    featured: false,
    published: false,
    order: 32,
    completedAt: null,
    seoTitle: "",
    seoDescription: "",
  },
  {
    title: "Nuwan & Kavini Homecoming Reception",
    slug: "nuwan-kavini-homecoming-reception",
    description:
      "A companion invitation site for the couple's homecoming reception, reusing the wedding invitation's design system for a second event.",
    fullDescription:
      "A companion invitation site for the couple's homecoming reception, reusing the wedding invitation's design system for a second event.",
    body: [
      "## Overview",
      "",
      "A companion invitation site for the couple's homecoming reception, reusing the wedding invitation's design system for a second event.",
    ].join("\n"),
    technologies: ["Next.js", "Vercel", "[CONFIRM any others]"],
    coverImage: "",
    liveUrl: "https://homecoming-reception.vercel.app",
    repoUrl: "",
    client: "Kavini & Nuwan [CONFIRM: real names OK, or anonymize to \"Private client\"?]",
    category: "Web / Event", // same string as #15 — see comment there
    featured: false,
    published: false,
    order: 33,
    completedAt: null,
    seoTitle: "",
    seoDescription: "",
  },
];
